#!/bin/bash
index=1
find /path/to/directory -type f -name "FILENAME" | while read -r file; do
    newname=$(basename "$file" | tr '[:upper:]' '[:lower:]')
    extension="${newname##*.}"
    filename="${newname%.*}"
    newname="${filename}_$index.$extension"
    mv "$file" "$(dirname "$file")/$newname"
    index=$((index+1))
done
